#!/bin/bash
echo "apt-get update -y && \ apt-get upgrade -y >> /var/log/update_script.log" > everyday_update.sh
sudo chmod 755 everyday_update.sh
sudo mv everyday_update.sh /etc/cron.daily
echo "0 4 * * 7 /etc/cron.daily/everyday_update.sh" | crontab
crontab -l
