#!/bin/bash

TARGET=/etc/crontab
BACKUP=/etc/.crontab_backup

if [ ! -e $BACKUP ]; then
	echo "Backup does not exist"
	sudo cp $TARGET $BACKUP
	exit 0
fi

MD5=`md5sum $TARGET | awk '{ print $1 }'`
MD5_BACKUP=`md5sum $BACKUP | awk '{ print $1 }'`

if [ -z $MD5 ] | [ -z $MD5_BACKUP ]; then
	echo "MD5 is empty."
fi

if [ "$MD5" != "$MD5_BACKUP" ]; then
	echo "Crontab has been modified" | mail -s "Report" root
fi

sudo cp $TARGET $BACKUP


if [ -e /etc/cron_hash.md5 ]; then
    if ! md5sum -c /etc/cron_hash.md5; then
	echo "Hash sum didn't match the previous value" | mail -s "Missmatch" root
	md5sum /etc/crontab > /etc/cron_hash.md5
    fi
else
    md5sum /etc/crontab > /etc/cron_hash.md5
fi

#To install the mail command: apt-get install mailutils